controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_hvac_submit:
    path: /api/hvac
    controller: App\Controller\HomepageController::submit
    methods: [POST]
